name: Get ProjectV2 ID
description:
  This action outputs the ProjectV2 ID using the Project number and Organization
  login name
author: Claudio Maradonna

branding:
  icon: 'check-square'
  color: 'purple'

inputs:
  token:
    description: GitHub Token
    required: true
  owner:
    description: Owner login name
    required: true
  owner_typology:
    description: Must be one of [ `organization`, `user` ]
    required: true
  project_number:
    description: ProjectV2 Number
    required: true

outputs:
  project_id:
    description: The ProjectV2 ID in long format

runs:
  using: node20
  main: dist/index.js
